### ISSUE TITLE
Argument networks not recognized

### ISSUE THREAD

**Issue by BOZG** [qdm12/docker-proxy-acl-alpine#1]
Having issues while trying to pass "-a networks".  Here's what my logs in Portainer look like:

2019/07/15 14:43:46 ✔️ Allowing endpoint containers
2019/07/15 14:43:46 ✔️ Allowing endpoint images
2019/07/15 14:43:46 ✔️ Allowing endpoint info
2019/07/15 14:43:46 ✔️ Allowing endpoint networks
2019/07/15 14:43:46 ✔️ Allowing endpoint post
2019/07/15 14:43:46 ✔️ Allowing endpoint volumes
2019/07/15 14:43:46 ✔️ Allowing endpoint exec
2019/07/15 14:43:46 ❌ Argument networks not recognized

**Comment by qdm12** [comment]
Hi there!

Thanks for trying my container. 
I spotted the error on my phone, I forgot to add `networks` to the allowed options in a startup check.

I'll fix it in a few hours and will close the issue once fixed.

**Comment by BOZG** [comment]
That was super quick! I noticed that exec and post don't work either (should have read the README more carefully first) and wondering if support for other endpoints is on the cards at the some point?

**Comment by qdm12** [comment]
Are exec and post other endpoints? I can add them, but it might take a few days as I am moving in currently and don't have internet really!

If you want to open a PR to add more endpoints, you're welcome to! You should have to git clone the repository, change main.go and docker build it and test it out. But I'll definitely look into it as soon as I settle!

**Comment by BOZG** [comment]
PRs are unfortunately way beyond my capabilities! Tecnativa's [Docker Socket Proxy](https://github.com/Tecnativa/docker-socket-proxy) that I'm currently using has a list of the various API endpoints as well as some notes about security issues relating to them. It doesn't create a new docker socket file like yours/titpetric's which is what I like! 

Good luck with the move!

**Comment by qdm12** [comment]
Hi there,

I have added (without testing though) all the other endpoints I found on Tecnativa's image readme. Let me know if they work or don't! I will add documentation for all endpoints later.
